# Generated by Django 4.1.2 on 2022-11-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('company_address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientInfo', to='myNewsApp.company')),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyInfo', to='myNewsApp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('sourced_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcingClient', to='myNewsApp.company')),
                ('subscribed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subUser', to='myNewsApp.subscriber')),
            ],
            options={
                'unique_together': {('url', 'sourced_client')},
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('body_text', models.TextField()),
                ('url', models.URLField(max_length=250)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcedStory', to='myNewsApp.source')),
                ('tagged_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagClient', to='myNewsApp.company')),
                ('tagged_company', models.ManyToManyField(related_name='tagCompany', to='myNewsApp.company')),
            ],
            options={
                'unique_together': {('url', 'tagged_client')},
            },
        ),
    ]
